documents: "src/**/*.tsx"
generates:
  src/generated/graphql.ts:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-react-apollo"
    config:
      avoidOptionals: true
hooks:
  afterOneFileWrite:
    - npx prettier --write
