type Query {
  divisions: [Division]
  division(divisionName: String): Division
}

type Division {
  divisionName: String
  divisionDisplayName: String
  numMembers: Int
  numDepartments: Int
  divisionColor: String
  members: [Member]
}

type Deparment {
  departmentName: String
  members: [Member]
}

type Member {
  name: String
  divisionName: String
  departmentName: String
  title: String
  location: String
  telephone: String
  mailAddress: String
}
