type Query {
  divisions: [Division]
}

type Division {
  divisionName: String
  numMembers: Int
  numDepartments: Int
  another: AnotherType
}

type AnotherType {
  anotherName: String
  anotherNumber: Int
}
