type Query {
  divisions: [Division]
  division(divisionName: String): Division
  departments: [Department]
  department(divisionName: String, departmentName: String): Department
}

type Division {
  divisionName: String
  divisionDisplayName: String
  divisionColor: String
  numDepartments: Int
  departments: [Department]
  numMembers: Int
  members: [Member]
}

type Department {
  departmentName: String
  departmentDisplayName: String
  numMembers: Int
  members: [Member]
}

type Member {
  name: String
  divisionDisplayName: String
  departmentDisplayName: String
  title: String
  location: String
  telephone: String
  mailAddress: String
  imageUrl: String
}
